// src/components/learnings/evolution-feed.tsx
// Significant milestones in how Aether's accumulated experience evolved.
// Milestones are rendered as generated by learningTimeline without
// reinterpretation of their labels or details.

import { cn } from "@/lib/utils";
import type { IntelligenceSummary, LearningMilestone } from "@/types/intelligence";

interface EvolutionFeedProps {
  summary: IntelligenceSummary;
}

const TIER_STYLES: Record<LearningMilestone["tier"], { dot: string; label: string }> = {
  foundation: { dot: "bg-sky-400", label: "Foundation" },
  growth: { dot: "bg-violet-400", label: "Growth" },
  maturity: { dot: "bg-emerald-400", label: "Maturity" },
};

function formatTimestamp(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function EvolutionFeed({ summary }: EvolutionFeedProps) {
  const { learningTimeline } = summary;

  if (learningTimeline.length === 0) {
    return (
      <section className="flex flex-col gap-12">
        <div className="flex items-start justify-between gap-8">
          <div className="max-w-2xl">
            <p className="text-[11px] uppercase tracking-[0.35em] text-emerald-400">
              EVOLUTION OVER TIME
            </p>

            <h2 className="mt-3 font-serif text-4xl tracking-tight text-white">
              Evolution Feed
            </h2>

            <p className="mt-4 text-lg leading-9 text-slate-400">
              Significant milestones that reveal how Aether's understanding matured through repeated missions.
            </p>
          </div>

          <p className="max-w-[240px] pt-6 text-right text-sm leading-relaxed text-slate-500">
            A timeline of meaningful shifts in accumulated experience.
          </p>
        </div>

        <div className="rounded-3xl border border-slate-800 bg-slate-900/50 px-6 py-10 text-center text-sm text-slate-500">
          No meaningful changes in Aether's accumulated experience have been recorded yet.
        </div>
      </section>
    );
  }

  return (
    <section className="flex flex-col gap-12">
      <div className="flex items-start justify-between gap-8">
        <div className="max-w-2xl">
          <p className="text-[11px] uppercase tracking-[0.35em] text-emerald-400">
            EVOLUTION OVER TIME
          </p>

          <h2 className="mt-3 font-serif text-4xl tracking-tight text-white">
            Evolution Feed
          </h2>

          <p className="mt-4 text-lg leading-9 text-slate-400">
            Significant milestones that reveal how Aether's understanding matured through repeated missions.
          </p>
        </div>

        <p className="max-w-[240px] pt-6 text-right text-sm leading-relaxed text-slate-500">
          A timeline of meaningful shifts in accumulated experience.
        </p>
      </div>

      <div className="flex flex-col rounded-2xl border border-slate-800 bg-slate-900/40 px-8 py-8 backdrop-blur-sm">
        {/* Evolution milestones should represent meaningful changes in
            accumulated experience rather than individual campaign events. */}
        {learningTimeline.map((milestone, i) => {
          const tier = TIER_STYLES[milestone.tier];
          const isLast = i === learningTimeline.length - 1;

          return (
            <div key={`${milestone.campaignId}-${milestone.label}`} className="flex gap-5 transition-all duration-300 hover:translate-x-1">
              {/* Connector */}
              <div className="flex flex-col items-center">
                <span className={cn("mt-1.5 h-2 w-2 shrink-0 rounded-full", tier.dot)} />
                {!isLast && <div className="mt-1 w-px flex-1 bg-slate-800" />}
              </div>

              {/* Content */}
              <div className={cn("flex flex-col gap-1", isLast ? "pb-0" : "pb-6")}>
                <div className="flex items-center gap-2">
                  <span className="text-lg font-medium text-slate-100">{milestone.label}</span>
                  <span className="rounded-full border border-slate-700 bg-slate-900 px-3 py-1 text-[11px] uppercase tracking-[0.25em] text-slate-500">
                    {tier.label}
                  </span>
                </div>
                <p className="text-[15px] leading-8 text-slate-300">{milestone.detail}</p>
                <p className="mt-2 text-sm leading-relaxed text-slate-500">
                  {formatTimestamp(milestone.timestamp)} · Mission #{milestone.campaignId}
                </p>
              </div>
            </div>
          );
        })}
      </div>
      <p className="text-[10px] leading-relaxed text-slate-600">
        Evolution milestones should represent meaningful shifts in accumulated
        experience rather than a complete log of campaign activity. Detailed
        mission records remain available in Archives.
      </p>
    </section>
  );
}